name: Java CI with Gradle

on:
  release:
    types: [ created ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin' # Formerly "Adopt OpenJDK"

    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm ci
      working-directory: client

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: server

    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: bootJar
        build-root-directory: server

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: server/build/libs/corona-test-management*.jar
